### ISSUE TITLE
Swift Package Manager support?

### ISSUE THREAD

**Issue by vinc3m1** [ybrid/opus-swift#1]
Seems like you may just need a Package.swift file?

https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

**Comment by FlorianAtNacamar** [comment]
Thank you very much for your input, Vince. I read the doc you provided and agreed. It should be possible to support SPM for developers who use Swift 5.3. I will take care of it.

**Comment by FlorianAtNacamar** [comment]
With version 0.8.0, Package.swift is added and SPM is supported.
